name: cars
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.0
  image_picker: ^1.0.4
  pdf: ^3.10.4
  open_file: ^3.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.0.4
  analyzer: 6.2.0

flutter:
  uses-material-design: true
